version: "3.9"

services:
  web:
    build: .
    container_name: enfekte_web
    env_file: .env.example.prod
    environment:
      # Uygulama ve healthcheck aynı portu kullansın
      PORT: "8000"
    ports:
      - "8000:8000"
    # Geliştirme için mount; prod'da genelde kaldırılır
    volumes:
      - ./:/app
    command: >
      gunicorn app:app
      --bind 0.0.0.0:8000
      --worker-class gthread
      --threads 8
      --timeout 180
      --log-level debug
      --access-logfile -
      --forwarded-allow-ips="*"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

